[package]
name = "rc5"
version = "0.1.0"
authors = ["Oleks Pickle <aleks.work2222@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = {version = "4.0.29", features = ["derive"]}
env_logger = "0.9.0"
log = "0.4.0"
rand = "0.8.5"

